name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - experiment-*
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: Get Version
        run: vercel --version
      - name: Reading Projects
        working-directory: ./apps/tc-apis
        run: vercel projects --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
      - name: link
        working-directory: ./apps/tc-apis
        run: vercel link --project=${{ secrets.VERCEL_PROJECT_ID }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --yes --debug
      - name: Pull Vercel Environment Information
        working-directory: ./apps/tc-apis
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   working-directory: ./apps/tc-apis
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./apps/tc-apis
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}